package RECURSION;

import java.util.ArrayList;
import java.util.Scanner;

// You are given a keypad (as shown in the diagram) and an array arr[ ] containing digits, your task is to list all possible words in any order which can be generated by pressing numbers in arr[] sequentially.

// Note: Number 0 and 1 do not map to any letters.
// You can return the words in any order, the driver code will print them in sorted order.

public class digitsFromPhone {

    static String[] key = {"","","abc","def","ghi","jkl","mno","pqrs","tuv","wxyz"};
    public static ArrayList<String> possibleWords(int[] arr) {
        // code here
    ArrayList<String> result  =  new ArrayList<>();
    if(arr.length==0)
    {
        return result;
    }
    
    helper(arr,0,"",result);
    return result;
    
    
    }
    
    public static void  helper(int[] arr, int index, String curr,ArrayList<String> result)
    {
        if(index==arr.length)
        {
            result.add(curr);
            return;
        }
        
        String letters=key[arr[index]];
        
        if(letters.length()==0)
        {
            helper(arr,index+1,curr,result);
            return;
        }
        
        for(int i=0;i<letters.length();i++)
        {
            helper(arr,index+1,curr+letters.charAt(i),result);
        }
    }


    public static void main(String[] args) {
        Scanner sc= new Scanner(System.in);
        System.out.println("Enter the array size");
        int n=sc.nextInt();
        int[] arr= new int[n];
        System.out.println("Enter the array element");
        for(int i=0;i<n;i++)
        {
            arr[i]=sc.nextInt();
        }

          
          ArrayList<String> l1 = possibleWords(arr);
          for(String s:l1)
          {
            System.out.println(s);
          }

    }
    
}
